// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.b2mml.domain.perform;

import es.uca.b2mml.domain.perform.EquipmentActualProperty;
import javax.persistence.Entity;

privileged aspect EquipmentActualProperty_Roo_Jpa_Entity {
    
    declare @type: EquipmentActualProperty: @Entity;
    
}
