// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.b2mml.domain.perform;

import es.uca.b2mml.domain.perform.ProductionPerformance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProductionPerformance_Roo_Configurable {
    
    declare @type: ProductionPerformance: @Configurable;
    
}
