// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.b2mml.domain.material;

import es.uca.b2mml.domain.material.MaterialLotStatus;

privileged aspect MaterialLotStatus_Roo_JavaBean {
    
    public String MaterialLotStatus.getName() {
        return this.name;
    }
    
    public void MaterialLotStatus.setName(String name) {
        this.name = name;
    }
    
}
