<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="links" nsURI="www.uca.es/modeling/weaving/wsdl" nsPrefix="mw">
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceRequirementLinks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//PerformanceRequirementLink" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceRequirementLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="execNode" eType="ecore:EClass http://www.eclipse.org/uml2/4.0.0/UML#//ExecutableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass http://serviceAnalyzer/messageCatalog#//TypeOperation"/>
  </eClassifiers>
</ecore:EPackage>
