// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.b2mml.domain.capability;

import es.uca.b2mml.domain.capability.EquipmentCapability;
import javax.persistence.Entity;

privileged aspect EquipmentCapability_Roo_Jpa_Entity {
    
    declare @type: EquipmentCapability: @Entity;
    
}
