// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.b2mml.domain.material;

import es.uca.b2mml.domain.material.MaterialLot;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MaterialLot_Roo_Configurable {
    
    declare @type: MaterialLot: @Configurable;
    
}
