// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.b2mml.domain.capability;

import es.uca.b2mml.domain.capability.PersonnelCapabilityProperty;
import javax.persistence.Entity;

privileged aspect PersonnelCapabilityProperty_Roo_Jpa_Entity {
    
    declare @type: PersonnelCapabilityProperty: @Entity;
    
}
