<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="serviceProcess" nsURI="www.uca.es/modeling/serviceProcess" nsPrefix="sp">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceProcess">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//ProcessFlowNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//ProcessFlowEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityPerformance" upperBound="-1"
        eType="#//ActivityPerformanceAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processPerformance" eType="#//ProcessPerformanceAnnotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessFlowEdge" abstract="true" eSuperTypes="#//FlowEdge">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="width" value="3"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessFlowNode" abstract="true" eSuperTypes="#//FlowNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityPerformanceAnnotation" eSuperTypes="#//LocalPerformanceAnnotation">
    <eAnnotations source="gmf.node">
      <details key="label.pattern" value="&lt;&lt;sapc>>"/>
      <details key="tool.name" value="Service Activity Performance Constraint"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="execNode" eType="#//ServiceActivity"
        eOpposite="#//ServiceActivity/annotation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manuallyAdded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="gmf.label">
        <details key="label.readOnly" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessPerformanceAnnotation" eSuperTypes="#//PerformanceAnnotation">
    <eAnnotations source="gmf.node">
      <details key="label.pattern" value="&lt;&lt;sppc>>"/>
      <details key="tool.name" value="Service Process Performance Constraint"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessControlFlow" eSuperTypes="#//ProcessFlowEdge #//ControlFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceActivity" eSuperTypes="#//ProcessFlowNode #//Activity">
    <eAnnotations source="gmf.node">
      <details key="tool.name" value="Service Activity"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#//ActivityPerformanceAnnotation"
        eOpposite="#//ActivityPerformanceAnnotation/execNode">
      <eAnnotations source="gmf.link">
        <details key="label" value="performance"/>
        <details key="style" value="dash"/>
        <details key="tool.name" value="Link Performance Annotation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessStart" eSuperTypes="#//ProcessFlowNode #//InitialNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessFinish" eSuperTypes="#//ProcessFlowNode #//FinalNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessDecision" eSuperTypes="#//ProcessFlowNode #//DecisionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessFork" eSuperTypes="#//ProcessFlowNode #//ForkNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessJoin" eSuperTypes="#//ProcessFlowNode #//JoinNode"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ExpressionLanguage">
    <eLiterals name="OCL"/>
    <eLiterals name="JML" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisitStatus">
    <eLiterals name="NOT_VISITED"/>
    <eLiterals name="VISITING" value="1"/>
    <eLiterals name="VISITED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NodeSide">
    <eLiterals name="INCOMING"/>
    <eLiterals name="OUTGOING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceAnnotation" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="concurrentUsers"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrentUsers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="1">
      <eAnnotations source="gmf.label">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secsTimeLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="0">
      <eAnnotations source="gmf.label">
        <details key="label.readOnly" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalPerformanceAnnotation" abstract="true"
      eSuperTypes="#//PerformanceAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="0">
      <eAnnotations source="gmf.label">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="1">
      <eAnnotations source="gmf.label">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//FlowEdge" eOpposite="#//FlowEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//FlowEdge" eOpposite="#//FlowEdge/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowEdge" abstract="true">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="width" value="3"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//FlowNode"
        eOpposite="#//FlowNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//FlowNode"
        eOpposite="#//FlowNode/outgoing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlow" abstract="true" eSuperTypes="#//FlowEdge">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="arrow"/>
      <details key="tool.name" value="Control Flow"/>
      <details key="label" value="condition,probability"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectFlow" abstract="true" eSuperTypes="#//FlowEdge">
    <eAnnotations source="gmf.link">
      <details key="style" value="dash"/>
      <details key="target.decoration" value="arrow"/>
      <details key="tool.name" value="Object Flow"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//FlowNode #//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="figure" value="es.uca.modeling.figures.CapsuleFigure"/>
      <details key="label.icon" value="false"/>
      <details key="tool.name" value="Executable Node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectNode" abstract="true" eSuperTypes="#//FlowNode #//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="label.icon" value="false"/>
      <details key="tool.name" value="Object Node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" abstract="true" eSuperTypes="#//FlowNode">
    <eAnnotations source="gmf.node">
      <details key="figure" value="es.uca.modeling.figures.FgFilledCircleFigure"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="30,30"/>
      <details key="tool.name" value="Start"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode" abstract="true" eSuperTypes="#//FlowNode">
    <eAnnotations source="gmf.node">
      <details key="figure" value="es.uca.modeling.figures.FgBgFilledCircleFigure"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="30,30"/>
      <details key="tool.name" value="Finish"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode" abstract="true" eSuperTypes="#//FlowNode">
    <eAnnotations source="gmf.node">
      <details key="figure" value="es.uca.modeling.figures.FgFilledRectangleFigure"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="15,30"/>
      <details key="tool.name" value="Fork"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinNode" abstract="true" eSuperTypes="#//FlowNode">
    <eAnnotations source="gmf.node">
      <details key="figure" value="es.uca.modeling.figures.FgFilledRectangleFigure"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="15,30"/>
      <details key="tool.name" value="Join"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode" abstract="true" eSuperTypes="#//FlowNode">
    <eAnnotations source="gmf.node">
      <details key="figure" value="es.uca.modeling.figures.DiamondFigure"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="30,30"/>
      <details key="tool.name" value="Decision"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
