<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="performanceWeaving"
    nsURI="www.uca.es/modeling/modisco/performanceWeaving" nsPrefix="pw">
  <eClassifiers xsi:type="ecore:EClass" name="WeavingModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performanceRequirement"
        lowerBound="1" eType="ecore:EClass http://www.eclipse.org/papyrus/MARTE/1#//GQAM/GaStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testMethod" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//MethodDeclaration"/>
  </eClassifiers>
</ecore:EPackage>
